name: Feature Request
description: Inquire about adding new Celest functionality!
title: "[Feature]: "
labels: [enhancement]
assignees:
  - Jai Willems
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the Celest feature report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: Tell us what addition you are seeking! What solutions for the addition have you considered? What is the motivation behind this feature?
      placeholder: Tell us what you want to see!
      value: "Here is a feature!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.1.6
        - 0.1.9
        - 0.2.0
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/JaiWillems/Celest/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
